setwd("/")
file_path <- "sample_text.txt"
paragraph <- paste(readLines(file_path),collapse =" ")
cat("PARAGRAPH:",paragraph,"\n")
cleaned_para <- gsub("[[:punct:]]","" ,paragraph)
words <- unlist(strsplit(cleaned_para,"\\s+"))
cat("NUMBER OF WORDS",length(words),"\n")
word_length_vector <- nchar(words)
longest_word_length <-max(word_length_vector)
longest_word <-words[word_length_vector==longest_word_length]
cat("MEAN WORD LENGTH:", as.integer(mean(word_length_vector)),"\n")
cat("LONGEST WORDS:",longest_word,"\n")
replace <- readline(prompt= "ENTER THE WORD TO BE REPLACED:")
replacement <-readline(prompt = "ENTER THE REPLACEMENT:")
replaced_para <- gsub(replace,replacement,paragraph)
cat("REPLACED PARAGRAPH:",replaced_para)
